#pragma once

namespace lse::events::player {
void CloseContainerEvent();
void OpenContainerScreenEvent();
void UseRespawnAnchorEvent();
void OpenInventoryEvent();
void PullFishingHookEvent();
void UseBucketPlaceEvent();
void UseBucketTakeEvent();
void ConsumeTotemEvent();
void SetArmorEvent();
void RemoveEffectEvent();
void BlockInteractedEvent();

void onJoin();
void onPreJoin();
void onLeft();
void onChat();
void onChangeDim();
void onPlayerSwing();
void onAttackEntity();
void onAttackBlock();
void onPlayerDie();
void onRespawn();
void onStartDestroyBlock();
void onDestroyBlock();
void onPlaceBlock();
void afterPlaceBlock();
void onJump();
void onDropItem();
void onTakeItem();
void onOpenContainer();
void onInventoryChange();
void onUseItem();
void onUseItemOn();
void onChangeArmorStand();
void onChangeSprinting();
void onSneak();
void onEat();
void onAte();
void onEffectAdded();
void onEffectUpdated();
void onRide();
void onUseFrameBlock();
void onExperienceAdd();
void onBedEnter();
void onPlayerInteractEntity();
} // namespace lse::events::player
